apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: "{{ .Values.service }}-{{ .Values.name }}-local-pvc"
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: "{{ .Values.size }}"
    storageClassName: "local-openebs-hostpath-{{ .Values.service }}-{{ .Values.name }}"
