services:
  rustic:
    build:
      context: ./rustic
      dockerfile: Dockerfile
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    environment:
      SFTP_HOST: "${SFTP_HOST}"
      SFTP_PORT: "${SFTP_PORT}"
      SFTP_USER: "${SFTP_USER}"
      SFTP_HOST_PUBKEY: "${SFTP_HOST_PUBKEY}"
      SFTP_USER_PRIVKEY: "${SFTP_USER_PRIVKEY}"
      SFTP_MOUNT_PATH_IN_DOCKER: "${SFTP_MOUNT_PATH_IN_DOCKER}"
      REMOTE_ENDPOINT: "${REMOTE_ENDPOINT}"
      REMOTE_BUCKET_NAME: "${REMOTE_BUCKET_NAME}"
      REMOTE_PATH: "${REMOTE_PATH}"
      REMOTE_ACCESS_KEY_ID: "${REMOTE_ACCESS_KEY_ID}"
      REMOTE_SECRET_ACCESS_KEY: "${REMOTE_SECRET_ACCESS_KEY}"
      REMOTE_ADMIN_USER: "${REMOTE_ADMIN_USER}"
      REMOTE_ADMIN_PASSWORD: "${REMOTE_ADMIN_PASSWORD}"
      RUSTIC_ENCRYPTION_PASSWORD: "${RUSTIC_ENCRYPTION_PASSWORD}"
    networks:
      - test-net
networks:
  test-net:
    external:
      name: test-net-external
