services:
  rustic:
    image: rustic-image:latest
    build:
      context: ./rustic
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./vars/test/rclone.conf.template:/tmp/rclone.conf.template
    environment:
      SFTP_HOST: "${SFTP_HOST}"
      SFTP_PORT: "${SFTP_PORT}"
      SFTP_USER: "${SFTP_USER}"
      SFTP_HOST_PUBKEY: "${SFTP_HOST_PUBKEY}"
      SFTP_USER_PRIVKEY: "${SFTP_USER_PRIVKEY}"
      REMOTE_ENDPOINT: "${REMOTE_ENDPOINT}"
      REMOTE_BUCKET_NAME: "${REMOTE_BUCKET_NAME}"
      REMOTE_PATH: "${REMOTE_PATH}"
      REMOTE_ACCESS_KEY_ID: "${REMOTE_ACCESS_KEY_ID}"
      REMOTE_SECRET_ACCESS_KEY: "${REMOTE_SECRET_ACCESS_KEY}"
      REMOTE_ADMIN_USER: "${REMOTE_ADMIN_USER}"
      REMOTE_ADMIN_PASSWORD: "${REMOTE_ADMIN_PASSWORD}"
      RUSTIC_ENCRYPTION_PASSWORD: "${RUSTIC_ENCRYPTION_PASSWORD}"
      VFS_CACHE_MAX_SIZE: "${VFS_CACHE_MAX_SIZE}"
    networks:
      - test-net
    command: "${COMMAND}"
networks:
  test-net:
    name: test-net-external
    external: true
