version: "3.8"

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./vars/test/test-1/host_id_ed25519:/etc/ssh/ssh_host_ed25519_key:ro
      - ./vars/test/test-1/user_id_ed25519.pub:/home/sftpuser/.ssh/keys/id_ed25519.pub:ro
    environment:
      SFTP_USER: sftpuser
    command: sftpuser::1001

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/rustic-backups;
      /usr/bin/mc admin user add myminio rustic-user rustic-password;
      /usr/bin/mc admin policy set myminio readwrite user=rustic-user;
      exit 0;
      "

  rustic:
    build:
      context: ./rustic
      dockerfile: Dockerfile
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    depends_on:
      - sftp
      - minio-setup
    environment:
      SFTP_HOST: sftp
      SFTP_PORT: 22
      SFTP_USER: sftpuser
      SFTP_HOST_PUBKEY: "${SFTP_HOST_PUBKEY}"
      SFTP_USER_PRIVKEY: "${SFTP_USER_PRIVKEY}"
      SFTP_MOUNT_PATH_IN_DOCKER: /mnt/sftp
      REMOTE_ENDPOINT: http://minio:9000
      REMOTE_BUCKET_NAME: rustic-backups
      REMOTE_PATH: /backups
      REMOTE_ACCESS_KEY_ID: rustic-user
      REMOTE_SECRET_ACCESS_KEY: rustic-password
      RUSTIC_ENCRYPTION_PASSWORD: your_encryption_password_here
