apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-image-builder
spec:
  template:
    spec:
      containers:
      - name: buildah
        image: quay.io/buildah/stable:latest
        env:
          - name: DOCKERFILE
            value: |-
{{ .Files.Get "Dockerfile" | indent 14 }}
          - name: ENTRYPOINT_SH
            value: |-
{{ .Files.Get "entrypoint.sh" | indent 14 }}
          - name: RUSTIC_TEMPLATE_TOML
            value: |-
{{ .Files.Get "rustic.template.toml" | indent 14 }}
          - name: IMAGE_NAME
            value: {{ .Values.image.name | quote }}
          - name: TAG
            value: {{ .Values.image.tag | quote }}
          - name: REGISTRY
            value: {{ .Values.image.registry | quote }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /tmp/workspace
          cd /tmp/workspace
          echo "$DOCKERFILE" > Dockerfile
          echo "$ENTRYPOINT_SH" > entrypoint.sh
          echo "$RUSTIC_TEMPLATE_TOML" > rustic.template.toml

          buildah bud --format docker -t ${IMAGE_NAME}:${TAG} -f Dockerfile .
          buildah tag ${IMAGE_NAME}:${TAG} ${REGISTRY}/${IMAGE_NAME}:${TAG}
          buildah push --tls-verify=false ${REGISTRY}/${IMAGE_NAME}:${TAG}
          echo "Image built and pushed successfully"
      restartPolicy: Never