apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-image-builder
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=dir:///tmp/workspace"
        - "--destination=docker.io/benjmanable/rustic:latest"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: build-context
          mountPath: /tmp/workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-config-json
    - name: build-context
      configMap:
        name: rustic-docker-context