{{- range $cronjob := $.Values.backups }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjob.id }}
  labels:
    app.kubernetes.io/name: {{ $cronjob.id }}
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/instance: api
spec:
  schedule: "{{ $cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rustic-backup
            image: "ghcr.io/rustic-rs/rustic:latest"
            command:
            - /bin/sh
            - -c
            - {{ $cronjob.command }}
          restartPolicy: OnFailure


{{- end }}   