apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rustic-local-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: local-openebs-hostpath
