---
- name: Create app group
  group:
    name: "{{ app_group }}"
    state: present

- name: Create app user
  user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    shell: /bin/bash
    state: present
    system: yes
    create_home: yes
    home: "/home/{{ app_user }}"

- name: Ensure cron is installed
  package:
    name: cron
    state: present
    update_cache: yes
    cache_valid_time: 3600
  notify: Start cron service

- name: Ensure Docker and dependencies are installed
  block:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install initial dependencies
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      when: not ansible_check_mode

  when: ansible_os_family == "Debian"

- name: Ensure flock is installed
  package:
    name: util-linux
    state: present

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
  loop:
    - "{{ base_app_path }}"
    - "{{ base_log_path }}"
    - "{{ lock_file_path }}"

- name: Add app_user to Docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: yes

- name: Verify FUSE availability
  command: modprobe fuse
  changed_when: false
  # Needed to load kernel module as root
