[repository]
repository = "opendal:s3"
repo-hot = "/backup/rustic"
password = "$REMOTE_KEY_ID"
cache-dir = "/persisted/rustic-cache"

# options for both parts
[repository.options]
access_key_id = "$REMOTE_KEY_ID"
secret_access_key = "$REMOTE_ACCESS_KEY"

# options only for hot part
[repository.options-hot]

# options only cold part
[repository.options-cold]
bucket = "$REMOTE_BUCKET_NAME"
root = "$REMOTE_PATH"
default_storage_class = "DEEP_ARCHIVE"