apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: local-openebs-hostpath-sftp-{{ .Values.name }}
    annotations:
        openebs.io/cas-type: local
        cas.openebs.io/config: |
            - name: StorageType
              value: hostpath
            - name: BasePath
              value: /var/local-openebs-hostpath/sftp/{{ .Values.name }}
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
