# helmfile.yaml
# Repositories for Helm charts
repositories:
  - name: openebs
    url: https://openebs.github.io/openebs

releases:
  - name: openebs-helpers
    namespace: default
    chart: "./openebs-helpers"
    version: "0.1.0"
    wait: true
  - name: openebs
    namespace: openebs
    chart: openebs/openebs
    version: ^4.1.2 # Specify the desired version of OpenEBS
    createNamespace: true
    needs:
      - default/openebs-helpers
    wait: true
    set:
      - name: engines.replicated.mayastor.enabled
        value: false
    values:
      - zfs-localpv:
          enabled: false
