image:
    name: "rustic"
    tag: "latest"
registry:
    domain: "docker.io"
    namespace: "namespace"
    username: ""
    password: ""
kaniko:
    secret_content: |
        {
            "auths": {
                "https://index.docker.io/v1/": {
                "auth": "xxxxxxxxxxxxxxx"
                }
            }
        }
