[repository]
repository = "opendal:s3"
repo-hot = "/persisted/rustic/repo_hot"
password = "$RUSTIC_ENCRYPTION_PASSWORD"
cache-dir = "/persisted/rustic/cache"

# options only for hot part
[repository.options-hot]

# options only cold part
[repository.options-cold]
bucket = "$REMOTE_BUCKET_NAME"
root = "$REMOTE_PATH"
default_storage_class = "DEEP_ARCHIVE"
endpoint = "$REMOTE_ENDPOINT"
access_key_id = "$REMOTE_ACCESS_KEY_ID"
secret_secret_access_key = "$REMOTE_SECRET_ACCESS_KEY"