rustic-to-ramo:
    - id: job-1
      name: job-1
      command: "date; echo Completed job 1"
      schedule: "* * * * *"
      origin:
          - host: "ftps-server.com"
            user: "user-1"
            password: "some-password"
            path: "/mnt/ftps"
#    - id: job-2
#      name: ...
